const fs=require('fs'),path=require('path'),crypto=require('crypto'),vm=require('vm'),assert=require('assert/strict');
const dir=path.resolve(__dirname,'..'),root=path.resolve(dir,'../../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const state=JSON.parse(fs.readFileSync(path.join(dir,'STATE.json')));
const result={status:'HANDOFF_WIP_SOURCE_REVIEW',productPinCount:0,manifestFilesChecked:0,phaseSyntaxOnly:true,rendererExecuted:false,productWrites:0};
for(const [name,pin]of Object.entries(state.sourcePins)){assert.equal(sha(fs.readFileSync(path.join(root,name))),pin,name);result.productPinCount++;}
assert.equal(state.goalComplete,false);assert.equal(state.fullCurrentNativeCycleComplete,false);assert.deepEqual(state.unitTests,{tests:798,cancelled:1,skipped:0,todo:0,pass:751,status:'FAIL',fail:46});
result.fixturePacks={};
for(const kind of ['date-axis','rest-state']){
 const base=path.join(dir,'verification',kind),m=JSON.parse(fs.readFileSync(path.join(base,'PORTABLE-MANIFEST.json')));let count=0;
 for(const [name,pin]of Object.entries(m.snapshot)){assert.equal(sha(fs.readFileSync(path.join(base,kind==='date-axis'?'snapshot':'',name))),pin);count++;}
 for(const [name,pin]of Object.entries(m.phaseFiles)){assert.equal(sha(fs.readFileSync(path.join(base,name))),pin);count++;}
 result.manifestFilesChecked+=count;result.fixturePacks[kind]={filesChecked:count,status:m.status,states:m.states?.length??null};
 const launch=fs.readFileSync(path.join(base,'launch.mjs'),'utf8');assert.ok(launch.indexOf("if(!process.argv.includes('--execute-reviewed'))")<launch.indexOf("const electron="));assert.ok(launch.includes('PREPARED_ONLY_NO_EXECUTION'));assert.ok(launch.includes("path.resolve(dir,'../../../../..')"));
 const run=fs.readFileSync(path.join(base,'run.cjs'),'utf8');assert.ok(run.includes("path.resolve(__dirname,'../../../../..')")||run.includes("path.resolve(dir,'../../../../..')"));assert.ok(run.includes('.omc/artifacts/card-ui-handoff-resume/'));assert.ok(run.includes('Refusing to overwrite or retry previous run')||run.includes('Existing run must be preserved'));assert.ok(run.includes('show:false')&&run.includes('nodeIntegration:false')&&run.includes('contextIsolation:true'));assert.ok(!run.includes('webSecurity:false'));
}
const original=fs.readFileSync(path.join(dir,'resume.mjs'),'utf8');
let code=original.replace(/^import .*;\r?\n/gm,'').replaceAll('import.meta.url',JSON.stringify('file:///public/repository/backend/ref/card-ui-handoff-20261003/resume.mjs'));
result.resumeMemoryCases=[];
for(const scenario of ['restored','already-current','existing-local-plan-preserved']){
 const savedPlan='public plan',existing=scenario==='restored'?null:scenario==='already-current'?savedPlan:'preserve existing';let writes=0,output;
 const mockFs={constants:{COPYFILE_EXCL:1},existsSync:p=>p.endsWith('PLAN.md')||existing!==null,readFileSync:p=>p.endsWith('card-ui-questionnaire.json')?JSON.stringify({scope:{template_total:101,in_scope_templates:94}}):p.endsWith('PLAN.md')?savedPlan:existing,mkdirSync:()=>{},copyFileSync:(a,b,flags)=>{assert.equal(existing,null);assert.equal(flags,1);writes++;}};
 const context=vm.createContext({fs:mockFs,path,crypto,fileURLToPath:u=>new URL(u).pathname,spawnSync:()=>({status:0,stdout:'codex/card-ui-resume-20261003\n'}),console:{log:text=>{output=JSON.parse(text);}}});vm.runInContext(code,context);assert.equal(output.planState,scenario);assert.equal(output.startsAgent,false);assert.equal(output.startsApp,false);assert.equal(writes,scenario==='restored'?1:0);result.resumeMemoryCases.push({scenario,writes,startsAgent:false,startsApp:false});
}
const accountDir=path.join(dir,'verification/account-chart'),accountManifest=JSON.parse(fs.readFileSync(path.join(accountDir,'PACK-MANIFEST.json')));let accountRecords=0;
const adaptations=[];
for(const r of accountManifest.records){const actual=fs.readFileSync(path.join(dir,r.target));assert.equal(sha(actual),r.portableSHA256);const original=fs.readFileSync(path.join(root,r.source));assert.equal(sha(original),r.originalSHA256);if(!r.loaderAdapted)assert.equal(sha(actual),sha(original));else {const a=original.toString().split(/\r?\n/),b=actual.toString().split(/\r?\n/);const changed=[];for(let i=0;i<Math.max(a.length,b.length);i++)if(a[i]!==b[i])changed.push({line:i+1,original:a[i]??null,portable:b[i]??null});adaptations.push({target:r.target,changedLineCount:changed.length,changed:changed.length<15?changed:'MULTILINE_PREFIX_RECOMPOSITION_CHECK_REQUIRED'});}accountRecords++;}
result.accountChart={recordsVerified:accountRecords,adaptations,portableExecution:'NOT_RUN',originalCandidateSourceApproval:'Excluded; review is portability and provenance only'};
const provenance=JSON.parse(fs.readFileSync(path.join(accountDir,'EXTRA20-PROVENANCE.json'))),prefixSource=fs.readFileSync(path.join(accountDir,provenance.prefixSource),'utf8'),prefix=prefixSource.slice(0,prefixSource.indexOf(provenance.prefixEndAnchor)),assembled=fs.readFileSync(path.join(accountDir,'extra-twenty.cjs'),'utf8');assert.equal(sha(Buffer.from(prefix)),provenance.prefixSHA256);assert.equal(sha(Buffer.from(assembled)),provenance.assembledSHA256);assert.ok(assembled.startsWith(prefix));const suffix=assembled.slice(prefix.length);assert.equal(suffix.at(-1),'\n');const extra=suffix.slice(0,-1);assert.equal(sha(Buffer.from(extra)),provenance.additionalSHA256);
const auditSource=fs.readFileSync(path.join(accountDir,provenance.additionalSource),'utf8');assert.equal(sha(Buffer.from(auditSource)),provenance.additionalSourceOriginalSHA256);assert.ok(auditSource.includes(extra.trimEnd()));result.accountChart.extraTwentyAssemblyByteExact=true;
const ignore=fs.readFileSync(path.join(accountDir,'.gitignore'),'utf8');assert.ok(ignore.includes('FOCUSED-CONSUMER-DRAFT.json'));assert.ok(ignore.includes('CONSUMER-RESULT.json'));result.accountChart.generatedOutputIgnoreCovered=true;
const policy=fs.readFileSync(path.join(root,'scripts/security/gitleaks.toml'),'utf8');assert.equal(sha(Buffer.from(policy)),'7dc06222f80c555035ad812709b28686f60409e997d330ddf9a846304e00af8e');const block=policy.slice(policy.indexOf('[[allowlists]]'),policy.indexOf('[extend]'));assert.ok(block.includes('targetRules = ["generic-api-key"]'));assert.ok(block.includes('condition = "AND"'));assert.ok(block.includes('regexTarget = "secret"'));const paths=[...block.matchAll(/'''(\(\?:\^\|\/\).*?)'''/g)].map(m=>new RegExp(m[1]));assert.equal(paths.length,8);const secretPattern=block.match(/regexes = \['''(.*?)'''\]/)[1],publicHash=sha(fs.readFileSync(path.join(root,'app/styles/tokens.css'))),hashRule=new RegExp(secretPattern);assert.ok(hashRule.test(publicHash));assert.equal(hashRule.test(publicHash.slice(0,-1)+'0'),false);assert.equal(hashRule.test('x'+publicHash),false);assert.equal(paths.some(r=>r.test('app/styles/tokens.css')),false);assert.equal(paths.some(r=>r.test('backend/ref/card-ui-handoff-20261003/verification/company/archive/SOURCE-RECEIPT.json.extra')),false);result.securityPolicy={exactConfigSha256:sha(Buffer.from(policy)),exactAllowedMetadataPaths:paths.length,publicStylesheetHashConfirmed:true,differentHashAndOutsidePathRejected:true,independentSecurityGateRun:false};
result.documentPins={};for(const name of ['AGENTS.md','backend/ref/card-ui-handoff-20261003/README.md','backend/ref/card-ui-handoff-20261003/PLAN.md','backend/ref/card-ui-handoff-20261003/STATE.json','backend/ref/card-ui-handoff-20261003/resume.mjs'])result.documentPins[name]=sha(fs.readFileSync(path.join(root,name)));
result.boundaries={complete10194Required:true,currentNativeIncomplete:true,unitSuiteFailedAcknowledged:true,companyQuestionnaireExcludedFromApproval:true,accountChartPack:'AVAILABLE_STATIC_REVIEW',privacyScope:'Inspected root docs and public date/rest/account source + hashes; no native images or private stores opened'};
fs.writeFileSync(path.join(__dirname,'HANDOFF-INDEPENDENT-CHECKS.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
