'use strict';
window.axisPublic=(()=>{
 const L=window.AthenaLib,M=L.BoardMount,R=L.BoardTemplateRegistry,host=document.getElementById('host'),draws=[];
 let frame=0,frameHandle;const frameClock=()=>{frame++;frameHandle=requestAnimationFrame(frameClock);};frameHandle=requestAnimationFrame(frameClock);
 const originalFill=CanvasRenderingContext2D.prototype.fillText;
 CanvasRenderingContext2D.prototype.fillText=function(text,x,y,...rest){const m=this.measureText(text),t=this.getTransform();draws.push({canvas:this.canvas,text:String(text),left:t.a*(x-m.actualBoundingBoxLeft)+t.c*y+t.e,right:t.a*(x+m.actualBoundingBoxRight)+t.c*y+t.e,bitmapWidth:this.canvas.width,bitmapHeight:this.canvas.height,frame});if(draws.length>10000)draws.splice(0,5000);return Reflect.apply(originalFill,this,[text,x,y,...rest]);};
 let mounted,body,adapter,session,period=null;
 const settle=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
 const values={};for(const slot of window.fixtureContract.slots)if(slot.mapping_id)values[slot.slot_id]=slot.f==='stk_nm'?'공개 합성 차트':slot.f==='stk_cd'?'QA0001':slot.format?.kind==='date'?'20260101':'12';
 function candles(next){const dates=[];if(next==='month'){for(let year=2010;year<=2026;year++)for(let month=1;month<=12;month++){if(year===2026&&month>1)break;dates.push(year+'-'+String(month).padStart(2,'0')+'-01');}}else{for(let day=Date.UTC(2010,0,1);day<=Date.UTC(2026,0,1);day+=7*86400000)dates.push(new Date(day).toISOString().slice(0,10));}return dates.map((time,i)=>({time,open:10+i%7,high:12+i%7,low:9+i%7,close:11+i%7,volume:20+i%5}));}
 async function mount(next){if(session){session.destroy();body.remove();}await R.loadBoard('137X-2');mounted=M.mountBoard(host,'137X-2',{...values},{identity:{code:'QA0001',name:'공개 합성 차트'}});M.collapsePrimaryMockup(mounted.primary.mountPoint);body=document.createElement('div');body.className='chart-card-body';body.style.cssText='flex:1;min-width:0;min-height:0';mounted.primary.mountPoint.append(body);
  adapter=L.AitsChartPanel.createAitsChartPanelAdapter({renderChart:(container,opts)=>L.ChartCard.createChartCard(container,opts)});session=await adapter.openPanel(body,{period:next,target:'stock',trId:next==='month'?'ka10083':'ka10082',candles:candles(next)},{panelId:'public-axis-'+next,stock:'QA0001',name:'공개 합성 차트',scopeId:'public-axis',generation:1});period=next;await document.fonts.ready;await settle();}
 async function state(next,edge,token){if(period!==next)await mount(next);document.getElementById('proof').textContent=token+' '+innerWidth+'×'+innerHeight;draws.length=0;const chart=session.renderer.chart,scale=chart.timeScale(),n=session.body.candles.length;
  const bars=Math.max(12,Math.floor(body.querySelector('.chart-price-pane').clientWidth/(next==='month'?8:7)));if(edge==='latest')scale.scrollToPosition(0,false);else if(edge==='first')scale.setVisibleLogicalRange({from:0,to:Math.min(n-1,bars)});else{const from=session.body.candles.findIndex(c=>String(c.time).startsWith('2019-'));if(from<1)throw Error('Required synthetic middle-year edge unavailable');scale.setVisibleLogicalRange({from,to:Math.min(n-1,from+bars)});}await settle();await new Promise(r=>setTimeout(r,180));return measure(edge);}
 function measure(edge){const issues=[],pane=body.querySelector('.chart-price-pane'),chartRoot=pane.querySelector('.tv-lightweight-charts'),axisCanvases=[...pane.querySelectorAll('table tr:last-child canvas')].filter(c=>c.width>200&&c.getBoundingClientRect().height>0&&c.getBoundingClientRect().height<=65),active=new Set(axisCanvases),lastFrames=new Map();for(const draw of draws)if(active.has(draw.canvas)&&draw.bitmapWidth===draw.canvas.width&&draw.bitmapHeight===draw.canvas.height)lastFrames.set(draw.canvas,Math.max(lastFrames.get(draw.canvas)||0,draw.frame));
  const ticks=draws.filter(d=>active.has(d.canvas)&&d.frame===lastFrames.get(d.canvas)&&d.bitmapWidth===d.canvas.width&&d.bitmapHeight===d.canvas.height).map(d=>({text:d.text,left:d.left,right:d.right,canvasWidth:d.bitmapWidth,canvasHeight:d.bitmapHeight,frame:d.frame}));if(!chartRoot||!axisCanvases.length)issues.push('primary-date-axis-not-mounted');if(!session.body.candles.length)issues.push('required-candles-empty');if(!ticks.length)issues.push('required-date-glyph-not-drawn');for(const t of ticks)if(!Number.isFinite(t.left)||!Number.isFinite(t.right))issues.push('date-glyph-boundary-unavailable');else if(t.left<-.5||t.right>t.canvasWidth+.5)issues.push('date-glyph-outside-canvas:'+t.text);
  const range=session.renderer.chart.timeScale().getVisibleLogicalRange();return {period,edge,candleCount:session.body.candles.length,mounted:!!chartRoot,axisCanvases:axisCanvases.map(c=>({width:c.width,height:c.height,cssWidth:c.getBoundingClientRect().width})),ticks,range,body:{width:body.clientWidth,height:body.clientHeight},issues};}
 function destroy(){if(session)session.destroy();if(adapter)adapter.destroyAll();cancelAnimationFrame(frameHandle);CanvasRenderingContext2D.prototype.fillText=originalFill;return {adapterSize:adapter?.size()||0};}
 return {state,measure,destroy};
})();
