'use strict';
// Never execute until root grants the isolated public renderer slot.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{app,BrowserWindow,session}=require('electron');
const mode=process.argv.find(a=>a.startsWith('--fixture-mode='))?.split('=')[1];if(!['baseline','candidate'].includes(mode))throw Error('Explicit fixture mode required');
const dir=__dirname,repoRoot=path.resolve(__dirname,'../../../../..'),out=path.join(repoRoot,'.omc/artifacts/card-ui-handoff-resume/date-axis/runs',mode),manifest=JSON.parse(fs.readFileSync(path.join(dir,'PORTABLE-MANIFEST.json'))),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const [file,pin]of Object.entries(manifest.phaseFiles))if(sha(fs.readFileSync(path.join(dir,file)))!==pin)throw Error('Frozen phase changed');for(const [file,pin]of Object.entries(manifest.snapshot))if(sha(fs.readFileSync(path.join(dir,'snapshot',file)))!==pin)throw Error('Frozen snapshot changed');
if(fs.existsSync(out))throw Error('Refusing to overwrite or retry previous run');fs.mkdirSync(out,{recursive:true});app.setName('AthenaPublicDateAxis-'+mode);app.setPath('userData',path.join(out,'isolated-public-profile'));app.disableHardwareAcceleration();
let win,paintCount=0;const states=[],captures=[],network=[],errors=[];const pause=ms=>new Promise(r=>setTimeout(r,ms));const call=(method,...args)=>win.webContents.executeJavaScript('axisPublic.'+method+'('+args.map(a=>JSON.stringify(a)).join(',')+')');
app.whenReady().then(async()=>{const isolated=session.fromPartition('axis-public-'+mode+'-'+process.pid);isolated.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','ws://*/*','wss://*/*']},(details,cb)=>{network.push({scheme:details.url.split(':')[0]});cb({cancel:true});});win=new BrowserWindow({show:false,width:2560,height:1392,webPreferences:{session:isolated,offscreen:true,sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('paint',()=>paintCount++);win.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message);});await win.loadFile(path.join(dir,mode+'.html'));await win.webContents.executeJavaScript('document.fonts.ready');
 for(const entry of manifest.states){win.setContentSize(entry.width,entry.height);await pause(180);const measured=await call('state',entry.period,entry.edge,mode+' / '+entry.name);states.push({...entry,viewport:win.getContentSize(),...measured});const before=paintCount;win.webContents.invalidate();await pause(140);const png=(await win.webContents.capturePage()).toPNG();fs.writeFileSync(path.join(out,entry.name+'.png'),png);captures.push({name:entry.name,sha256:sha(png),paintBefore:before,paintAfter:paintCount});}
 const cleanup=await call('destroy'),sourceUnchanged=Object.entries(manifest.snapshot).every(([file,pin])=>sha(fs.readFileSync(path.join(dir,'snapshot',file)))===pin);const report={mode,pid:process.pid,ppid:process.ppid,states,captures,cleanup,sourceUnchanged,network,errors,scope:manifest.scope,productWrites:0,privateReads:0};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({mode,pid:process.pid,states:states.length,captures:captures.length,issues:states.flatMap(s=>s.issues.map(issue=>({state:s.name,issue}))),cleanup,sourceUnchanged,network,errors}));win.destroy();app.quit();
}).catch(error=>{fs.writeFileSync(path.join(out,'run-error.json'),JSON.stringify({pid:process.pid,error:String(error.stack||error)},null,2));console.error(error);if(win&&!win.isDestroyed())win.destroy();app.exit(1);});
